/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as NewsRouteImport } from './routes/news'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as ApiPublicSiteHostRouteImport } from './routes/api.public.site-host'
import { Route as ApiPublicChatAggregateRouteImport } from './routes/api.public.chat-aggregate'
import { Route as ApiAdminGenerateToolsRouteImport } from './routes/api/admin/generate-tools'
import { Route as ApiAdminGeneratePromptsRouteImport } from './routes/api/admin/generate-prompts'
import { Route as ApiAdminGenerateNewsRouteImport } from './routes/api/admin/generate-news'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TopicsRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteHostRoute = ApiPublicSiteHostRouteImport.update({
  id: '/api/public/site-host',
  path: '/api/public/site-host',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatAggregateRoute = ApiPublicChatAggregateRouteImport.update({
  id: '/api/public/chat-aggregate',
  path: '/api/public/chat-aggregate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGenerateToolsRoute = ApiAdminGenerateToolsRouteImport.update({
  id: '/api/admin/generate-tools',
  path: '/api/admin/generate-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGeneratePromptsRoute = ApiAdminGeneratePromptsRouteImport.update({
  id: '/api/admin/generate-prompts',
  path: '/api/admin/generate-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGenerateNewsRoute = ApiAdminGenerateNewsRouteImport.update({
  id: '/api/admin/generate-news',
  path: '/api/admin/generate-news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/news': typeof NewsRoute
  '/prompts': typeof PromptsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/admin/generate-news': typeof ApiAdminGenerateNewsRoute
  '/api/admin/generate-prompts': typeof ApiAdminGeneratePromptsRoute
  '/api/admin/generate-tools': typeof ApiAdminGenerateToolsRoute
  '/api/public/chat-aggregate': typeof ApiPublicChatAggregateRoute
  '/api/public/site-host': typeof ApiPublicSiteHostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/news': typeof NewsRoute
  '/prompts': typeof PromptsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/tools': typeof ToolsIndexRoute
  '/api/admin/generate-news': typeof ApiAdminGenerateNewsRoute
  '/api/admin/generate-prompts': typeof ApiAdminGeneratePromptsRoute
  '/api/admin/generate-tools': typeof ApiAdminGenerateToolsRoute
  '/api/public/chat-aggregate': typeof ApiPublicChatAggregateRoute
  '/api/public/site-host': typeof ApiPublicSiteHostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/news': typeof NewsRoute
  '/prompts': typeof PromptsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/admin/generate-news': typeof ApiAdminGenerateNewsRoute
  '/api/admin/generate-prompts': typeof ApiAdminGeneratePromptsRoute
  '/api/admin/generate-tools': typeof ApiAdminGenerateToolsRoute
  '/api/public/chat-aggregate': typeof ApiPublicChatAggregateRoute
  '/api/public/site-host': typeof ApiPublicSiteHostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/news'
    | '/prompts'
    | '/topics'
    | '/tools/$slug'
    | '/topics/$slug'
    | '/tools/'
    | '/api/admin/generate-news'
    | '/api/admin/generate-prompts'
    | '/api/admin/generate-tools'
    | '/api/public/chat-aggregate'
    | '/api/public/site-host'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/news'
    | '/prompts'
    | '/topics'
    | '/tools/$slug'
    | '/topics/$slug'
    | '/tools'
    | '/api/admin/generate-news'
    | '/api/admin/generate-prompts'
    | '/api/admin/generate-tools'
    | '/api/public/chat-aggregate'
    | '/api/public/site-host'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/news'
    | '/prompts'
    | '/topics'
    | '/tools/$slug'
    | '/topics/$slug'
    | '/tools/'
    | '/api/admin/generate-news'
    | '/api/admin/generate-prompts'
    | '/api/admin/generate-tools'
    | '/api/public/chat-aggregate'
    | '/api/public/site-host'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  NewsRoute: typeof NewsRoute
  PromptsRoute: typeof PromptsRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiAdminGenerateNewsRoute: typeof ApiAdminGenerateNewsRoute
  ApiAdminGeneratePromptsRoute: typeof ApiAdminGeneratePromptsRoute
  ApiAdminGenerateToolsRoute: typeof ApiAdminGenerateToolsRoute
  ApiPublicChatAggregateRoute: typeof ApiPublicChatAggregateRoute
  ApiPublicSiteHostRoute: typeof ApiPublicSiteHostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-host': {
      id: '/api/public/site-host'
      path: '/api/public/site-host'
      fullPath: '/api/public/site-host'
      preLoaderRoute: typeof ApiPublicSiteHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat-aggregate': {
      id: '/api/public/chat-aggregate'
      path: '/api/public/chat-aggregate'
      fullPath: '/api/public/chat-aggregate'
      preLoaderRoute: typeof ApiPublicChatAggregateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/generate-tools': {
      id: '/api/admin/generate-tools'
      path: '/api/admin/generate-tools'
      fullPath: '/api/admin/generate-tools'
      preLoaderRoute: typeof ApiAdminGenerateToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/generate-prompts': {
      id: '/api/admin/generate-prompts'
      path: '/api/admin/generate-prompts'
      fullPath: '/api/admin/generate-prompts'
      preLoaderRoute: typeof ApiAdminGeneratePromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/generate-news': {
      id: '/api/admin/generate-news'
      path: '/api/admin/generate-news'
      fullPath: '/api/admin/generate-news'
      preLoaderRoute: typeof ApiAdminGenerateNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TopicsRouteChildren {
  TopicsSlugRoute: typeof TopicsSlugRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsSlugRoute: TopicsSlugRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  NewsRoute: NewsRoute,
  PromptsRoute: PromptsRoute,
  TopicsRoute: TopicsRouteWithChildren,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiAdminGenerateNewsRoute: ApiAdminGenerateNewsRoute,
  ApiAdminGeneratePromptsRoute: ApiAdminGeneratePromptsRoute,
  ApiAdminGenerateToolsRoute: ApiAdminGenerateToolsRoute,
  ApiPublicChatAggregateRoute: ApiPublicChatAggregateRoute,
  ApiPublicSiteHostRoute: ApiPublicSiteHostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
