-- Re-seed tools and news_posts for local/dev environments.
-- Safe to re-run: tools upsert by slug, news upsert by url.

INSERT INTO public.tools (
  name, slug, vendor, category, description_short, discover_summary, pro_summary,
  url, pro_tags, discover_tags, rating, cost_tier, audience
) VALUES
('Claude','claude','Anthropic','Chat & Reasoning','Anthropic''s flagship reasoning model with long-context analysis.','A super smart writing and thinking buddy that''s great at long, careful answers.','Frontier LLM with 200k context, strong tool use, excellent for code review, legal/technical drafting, RAG.','https://claude.ai',ARRAY['200k-context','tool-use','XML-prompts','vision'],ARRAY['friendly','careful'],4.8,'freemium','pro'),
('ChatGPT','chatgpt','OpenAI','Chat & Reasoning','The most popular general-purpose AI assistant.','Ask anything — writing, ideas, homework help, recipes.','GPT-5 family, code interpreter, custom GPTs, plugins, multimodal I/O.','https://chat.openai.com',ARRAY['code-interpreter','custom-gpts','assistants-api'],ARRAY['easy','popular'],4.7,'freemium','both'),
('Grok 4','grok','xAI','Chat & Reasoning','xAI''s real-time, X-integrated assistant.','Knows what''s happening on social media right now.','Live web/X access, function calling, competitive reasoning benchmarks.','https://grok.x.ai',ARRAY['real-time','function-calling','x-integration'],ARRAY['live','witty'],4.4,'paid','both'),
('Gemini','gemini','Google','Chat & Reasoning','Google''s multimodal AI integrated with Workspace.','Helps in Gmail, Docs, and Search — like a Google-powered helper.','Gemini 2.5 Pro, native multimodal, 1M+ token context, Workspace integration.','https://gemini.google.com',ARRAY['1m-context','workspace','multimodal'],ARRAY['google','everywhere'],4.6,'freemium','both'),
('Perplexity','perplexity','Perplexity AI','Chat & Reasoning','AI search engine with cited answers.','Like Google but it answers your question with sources.','Sonar models, multi-source retrieval, focus modes, Pro Search agent.','https://perplexity.ai',ARRAY['rag','citations','sonar'],ARRAY['search','sources'],4.7,'freemium','both'),
('Cursor','cursor','Anysphere','Coding & Building','AI-first code editor built on VS Code.','A coding app that writes code with you.','Composer, agent mode, codebase indexing, multi-file edits, tab completion.','https://cursor.sh',ARRAY['agent-mode','codebase-rag','vscode-fork'],ARRAY['coding'],4.8,'freemium','pro'),
('GitHub Copilot','github-copilot','GitHub','Coding & Building','Inline AI code completion across IDEs.','Auto-completes code as you type.','Copilot Chat, Workspace, enterprise SKUs, IDE integrations.','https://github.com/features/copilot',ARRAY['ide-integration','enterprise','chat'],ARRAY['autocomplete'],4.5,'paid','pro'),
('Claude Artifacts','claude-artifacts','Anthropic','Coding & Building','Interactive code/UI sandbox inside Claude.','Builds little apps right in the chat for you to try.','Live preview of HTML/React/SVG/Mermaid generated by Claude.','https://claude.ai',ARRAY['live-preview','react','svg'],ARRAY['sandbox'],4.6,'freemium','pro'),
('Midjourney','midjourney','Midjourney','Creative & Media','Premier text-to-image generator.','Type a description, get a beautiful picture.','v7 model, style references, image weights, Discord + Web UI.','https://midjourney.com',ARRAY['style-ref','seeds','remix'],ARRAY['art','images'],4.8,'paid','both'),
('Kling AI','kling','Kuaishou','Creative & Media','High-fidelity AI video generation.','Turn a sentence into a short video clip.','Kling 1.6 Pro, image-to-video, motion brush, lip sync.','https://klingai.com',ARRAY['i2v','motion-brush','lip-sync'],ARRAY['video','easy'],4.5,'freemium','both'),
('Runway','runway','Runway','Creative & Media','Pro AI video, editing, and effects suite.','Movie-magic editing powered by AI.','Gen-4, Act-One, multi-motion brush, green screen, frame interpolation.','https://runwayml.com',ARRAY['gen-4','act-one','vfx'],ARRAY['filmmaking'],4.6,'paid','pro'),
('ElevenLabs','elevenlabs','ElevenLabs','Creative & Media','Best-in-class AI voice generation and cloning.','Make any voice say anything.','Multilingual v2, voice cloning, dubbing, conversational agents API.','https://elevenlabs.io',ARRAY['voice-cloning','dubbing','agents-api'],ARRAY['voices','audio'],4.8,'freemium','both'),
('Zapier Agents','zapier-agents','Zapier','Productivity & Automation','AI agents across 7000+ app integrations.','Robots that connect your apps and do tasks for you.','Multi-step agents, tools across Zapier ecosystem, triggers & schedules.','https://zapier.com/agents',ARRAY['7000+integrations','agents','triggers'],ARRAY['automation'],4.4,'freemium','pro'),
('Lindy','lindy','Lindy','Productivity & Automation','Build no-code AI employees and workflows.','Hire a digital assistant in minutes.','Agent builder, Gmail/Calendar/CRM tools, phone agents, multi-agent.','https://lindy.ai',ARRAY['agent-builder','phone','crm'],ARRAY['assistants'],4.5,'paid','pro'),
('n8n','n8n','n8n','Productivity & Automation','Open-source workflow automation with AI nodes.','Drag-and-drop way to wire up automations.','Self-hostable, LangChain nodes, code nodes, 400+ integrations.','https://n8n.io',ARRAY['self-host','langchain','open-source'],ARRAY['workflows'],4.7,'freemium','pro'),
('The Rundown AI','the-rundown-ai',NULL,'Research & Knowledge','Daily AI news + tutorials newsletter.','A short daily email that tells you what''s new in AI.','Curated industry signal, deep-dives, tool comparisons, courses.','https://therundown.ai',ARRAY['newsletter','industry'],ARRAY['daily','easy'],4.5,'free','both'),
('TLDR AI','tldr-ai',NULL,'Research & Knowledge','5-minute AI news digest.','The shortest way to keep up with AI.','Concise summaries of papers, launches, and tooling.','https://tldr.tech/ai',ARRAY['summaries'],ARRAY['quick','simple'],4.4,'free','discover'),
('MIT Technology Review AI','mit-tech-review-ai','MIT','Research & Knowledge','In-depth AI journalism and analysis.','Big magazine-style stories about how AI is changing the world.','Long-form reporting, policy, research breakdowns, interviews.','https://technologyreview.com/topic/artificial-intelligence',ARRAY['long-form','policy','research'],ARRAY['serious'],4.6,'paid','pro'),
('OpenRouter','openrouter','OpenRouter','Specialized','Unified API for hundreds of LLMs.','One key, every AI model.','Provider routing, fallbacks, cost analytics, OpenAI-compatible API.','https://openrouter.ai',ARRAY['unified-api','routing','byok'],ARRAY['developer'],4.7,'freemium','pro'),
('Synthesia','synthesia','Synthesia','Specialized','AI avatar video generator for training and marketing.','Make videos with realistic AI presenters.','230+ avatars, 140+ languages, custom avatars, brand kits.','https://synthesia.io',ARRAY['avatars','enterprise','localization'],ARRAY['videos','presenters'],4.6,'paid','both')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  vendor = EXCLUDED.vendor,
  category = EXCLUDED.category,
  description_short = EXCLUDED.description_short,
  discover_summary = EXCLUDED.discover_summary,
  pro_summary = EXCLUDED.pro_summary,
  url = EXCLUDED.url,
  pro_tags = EXCLUDED.pro_tags,
  discover_tags = EXCLUDED.discover_tags,
  rating = EXCLUDED.rating,
  cost_tier = EXCLUDED.cost_tier,
  audience = EXCLUDED.audience;

CREATE UNIQUE INDEX IF NOT EXISTS news_posts_url_unique ON public.news_posts (url);

INSERT INTO public.news_posts (title, summary, content, source, url, published_at)
VALUES
  (
    'Open-source AI agents are moving into production',
    'Teams are adopting agent workflows for support, ops, and internal automation.',
    'Across startups and enterprise teams, open-source agent frameworks are being deployed with tighter guardrails, clearer evaluation loops, and role-based tool access. The trend is toward practical, domain-scoped agents rather than fully autonomous systems.',
    'PiHLAI Briefing',
    'https://example.com/news/open-source-ai-agents-production',
    now() - interval '1 day'
  ),
  (
    'Model providers compete on latency and cost',
    'Vendors are shipping faster inference tiers as teams optimize for real-time UX.',
    'Inference pricing pressure is accelerating new low-latency model variants designed for chat, support, and coding copilots. Teams are increasingly routing traffic by task complexity to balance quality and spend.',
    'PiHLAI Briefing',
    'https://example.com/news/model-latency-cost-competition',
    now() - interval '2 days'
  ),
  (
    'AI governance tooling matures',
    'Policy, audit, and observability features are becoming standard in AI stacks.',
    'More platforms now include model-level logs, prompt/response retention controls, and configurable policy checks. This helps teams move from experimentation to repeatable, compliant production workflows.',
    'PiHLAI Briefing',
    'https://example.com/news/ai-governance-tooling',
    now() - interval '3 days'
  ),
  (
    'Retrieval quality becomes a top priority',
    'Better chunking and ranking strategies are outperforming larger context windows alone.',
    'Teams are investing in retrieval pipeline quality: corpus curation, hybrid search, metadata-aware ranking, and answer grounding. Results show that retrieval discipline often matters more than simply increasing model context.',
    'PiHLAI Briefing',
    'https://example.com/news/retrieval-quality-priority',
    now() - interval '4 days'
  ),
  (
    'Multimodal models reshape creative workflows',
    'Image, video, and audio generation are converging in unified creative pipelines.',
    'Creative teams are chaining image generation, video editing, and voice synthesis into single workflows. New model releases emphasize consistency across modalities and tighter brand-control features.',
    'PiHLAI Briefing',
    'https://example.com/news/multimodal-creative-workflows',
    now() - interval '5 days'
  ),
  (
    'Enterprise AI adoption shifts from pilots to production',
    'Companies are standardizing on evaluation, security, and cost controls.',
    'After years of experimentation, enterprise teams are deploying AI with formal SLAs, audit trails, and budget guardrails. Platform teams are consolidating vendor sprawl into governed internal toolchains.',
    'PiHLAI Briefing',
    'https://example.com/news/enterprise-ai-production',
    now() - interval '6 days'
  )
ON CONFLICT (url) DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  content = EXCLUDED.content,
  source = EXCLUDED.source,
  published_at = EXCLUDED.published_at;
